### ISSUE TITLE
Create Database 

### ISSUE THREAD

**Issue by thesauravkarmakar** [thesauravkarmakar/AidZeeCord#2]
Store the conversation's onto a database.

**Comment by lordvins226** [comment]
Hi. Have you found a database we can use ?

**Comment by thesauravkarmakar** [comment]
> Hi. Have you found a database we can use ?

No, you can create according to you like in MongoDB. But if you can go for Cloud-Based solutions like Firebase, it would be good.

**Comment by haidarrifki** [comment]
is this already done? i can work on this if not done yet

**Comment by thesauravkarmakar** [comment]
> is this already done? i can work on this if not done yet

It's not done yet. I'm assigning it to you.

**Comment by haidarrifki** [comment]
> > is this already done? i can work on this if not done yet
> 
> It's not done yet. I'm assigning it to you.

thanks! i have done and already create pull request #3 
let me know if something is missing.
